apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: v1
  template:
    metadata:
      labels:
        app: my-app
        version: v1
    spec:
      containers:
        - name: spring-boot-container-v1
          image: public.ecr.aws/q0j4m6z6/rahul87096/spring-boot-app:v2
          ports:
            - containerPort: 8080
