apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 80      # Service port (optional)
      targetPort: 8080  # Port inside the container
      nodePort: 30008  # Exposed on each node
  type: NodePort
