apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service-v1
spec:
  type: ClusterIP
  selector:
    app: my-app
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
