name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/demo-0.0.1-SNAPSHOT.jar

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download JAR from Artifact
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: target/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-demo:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-demo:latest


  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 & Deploy Docker Image
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo -i
            
            echo "Logging into Docker Hub..."
            sudo docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"

            echo "Pulling latest image from Docker Hub..."
            sudo docker pull rahul87096/spring-boot-demo:latest

            echo "Running the new container..."
            sudo docker run -d --name my-spring-app -p 9090:8080 rahul87096/spring-boot-demo:latest

