name: Docker Test in Self-Hosted Runner

on:
  push:
    branches:
      - runner

jobs:
  setup-and-run-docker:
    runs-on: self-hosted  # Ensure the job runs on your self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          sudo yum update -y || sudo apt update -y
          sudo yum install -y docker || sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          newgrp docker  # Apply changes immediatelyy
          docker --version  # Verify Docker is installed

      - name: Run Docker Hello-World
        run: docker run hello-world

      - name: Pull and Run Nginx Container
        run: |
          docker pull nginx
          docker run -d -p 8080:80 --name my-nginx nginx

      - name: Verify Running Containers
        run: docker ps -a
